// Fictional examples, loaded only into the isolated, local preview database.
export const previewProviders = [
  { id: "the-sunday-table", name: "The Sunday Table", category: "food", summary: "A full fridge. One less thing on your mind.", description: "Comforting family meals, cooked in small batches and delivered ready to warm. A little space back in your evening, with something nourishing on the table.", suburbs: ["Richmond", "Hawthorn", "Kew", "Abbotsford"], mode: "Delivered", price: "Example: $85 / family meal box", availability: "Example: Wednesday & Friday deliveries", included: ["Three generous family meals", "A choice of vegetarian dishes", "Heating and ingredient information", "Delivery details agreed before confirmation"] },
  { id: "kindred-home", name: "Kindred Home", category: "cleaning", summary: "A fresh home, and room to breathe.", description: "Thoughtful home cleaning that fits around family life. Tell us which spaces would make the biggest difference, and we’ll agree a practical plan together.", suburbs: ["Richmond", "Hawthorn", "Kew", "Camberwell"], mode: "At home", price: "Example: from $140 / visit", availability: "Example: weekday visits", included: ["Kitchen and bathroom refresh", "Floors and everyday surfaces", "A clear quote before you decide", "One-off or regular visits"] },
  { id: "a-little-order", name: "A Little Order", category: "life-admin", summary: "Make room for what matters to you.", description: "Friendly, practical help with the cupboards, paperwork and everyday tasks that keep piling up. Start with one small space and a manageable next step.", suburbs: ["Hawthorn", "Kew", "Camberwell", "Richmond"], mode: "At home", price: "Example: $180 / two-hour session", availability: "Example: Tuesday to Thursday", included: ["A two-hour organising session", "A plan for one priority space", "Simple systems you can keep using", "A judgement-free approach"] },
  { id: "little-days-care", name: "Little Days Care", category: "postpartum-carers", summary: "An extra pair of hands for your family.", description: "An example of how a family-care agency could introduce its services on Village. Enquiries help agree the tasks, experience and checks needed before any arrangement.", suburbs: ["Richmond", "Abbotsford", "Hawthorn"], mode: "At home", price: "Example: quote after an introduction", availability: "Example: enquire about your preferred days", included: ["Discuss your family’s routine", "Agree the help you need", "Review relevant qualifications and checks directly", "Confirm costs before making a decision"] },
  { id: "the-evening-kitchen", name: "The Evening Kitchen", category: "food", summary: "Good food for the beautifully busy days.", description: "An example meal provider with flexible portions and a weekly rotating menu. Choose a few easy dinners and enjoy a slower evening.", suburbs: ["Camberwell", "Kew", "Hawthorn"], mode: "Delivered", price: "Example: from $65 / meal bundle", availability: "Example: weekly delivery", included: ["Flexible meal bundles", "Family and smaller portions", "Ingredient information", "A delivery window agreed with you"] },
  { id: "space-to-start", name: "Space to Start", category: "life-admin", summary: "A gentler start to a lighter week.", description: "An example online organising service for planning household tasks and making a manageable routine. Work through one priority together, from wherever you feel comfortable.", suburbs: ["Online"], mode: "Online", price: "Example: $75 / session", availability: "Example: online appointments", included: ["A 45-minute online session", "Choose your own priority", "A short practical action plan", "No travel needed"] },
] as const;
