"use client";
import { useEffect, useState, type CSSProperties, type FormEvent } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { services } from "@/content/services";
import { useVillage } from "@/components/village/VillageProvider";
import VillageMark from "@/components/ui/VillageMark";
import { appApi, useApp, useAppData } from "./AppContext";
import { AppIcon, Empty, ErrorBox, Heading, Loading, ProviderArt, ProviderCard, RequestRow, SaveProviderAction, ServiceIcon, SignInPrompt } from "./AppUI";
import type { AppUser, Listing, SupportRequest } from "@/lib/app-types";

function useDirectory() {
  const { user } = useApp();
  const directory = useAppData<{ providers: Listing[] }>("providers");
  const saved = useAppData<{ providers: Listing[] }>("saved", user?.role === "family");
  return { directory, saved, savedIds: saved.data?.providers.map(p => p.id) || [] };
}
function VillageOrbit({ lit }: { lit: string[] }) {
  return <div className="va-orbit" aria-label="Explore support around your village"><div className="va-orbit-ring"/><div className="va-orbit-centre"><VillageMark/><strong>You</strong><small>at the heart of it</small></div>{services.map((service, i) => <Link key={service.slug} href={`/app/explore?category=${service.slug}`} className={`va-orbit-node ${lit.includes(service.slug) ? "is-lit" : ""}`} style={{ "--x": `${50 + 39 * Math.cos(i * Math.PI / 4 - Math.PI / 2)}%`, "--y": `${50 + 39 * Math.sin(i * Math.PI / 4 - Math.PI / 2)}%` } as CSSProperties} aria-label={`Find ${service.shortTitle.toLowerCase()}`}><ServiceIcon slug={service.slug}/><span>{service.shortTitle}</span></Link>)}</div>;
}
export function AppHome() {
  const { user, mode, setSession, refresh } = useApp(); const router = useRouter();
  const { directory, saved, savedIds } = useDirectory();
  const requests = useAppData<{ requests: SupportRequest[] }>("requests", user?.role === "family");
  const { draft } = useVillage();
  const [busy, setBusy] = useState(false), [error, setError] = useState("");
  const offers = requests.data?.requests.filter(r => r.status === "offered" || r.status === "delivered") || [];
  const lit = [...new Set([...draft.needs, ...(saved.data?.providers.map(p => p.category) || [])])];
  async function tryPreview() { setBusy(true); try { const result = await appApi<{ user: AppUser; mode: "preview" }>("preview", { role: "family" }); setSession(result); refresh(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  useEffect(() => { if (user?.role === "provider") router.replace("/app/partner"); if (user?.role === "owner") router.replace("/app/owner"); }, [user?.role, router]);
  return <><section className="va-welcome"><div><p className="va-eyebrow">{user ? `WELCOME TO YOUR VILLAGE, ${user.name.split(" ")[0]}` : "A LITTLE HELP, ALL AROUND YOU"}</p><h1>A little support.<br/><em>A lot more room<br className="va-desktop-break"/> to breathe.</em></h1><p>Meals sorted. A lighter home. An extra pair of hands. Bring together the support that feels right for you.</p><div className="va-actions">{!user && mode === "preview" ? <button className="va-button" disabled={busy} onClick={tryPreview}>{busy ? "Opening your village…" : "Try the family app"}<AppIcon name="arrow" size={18}/></button> : <Link className="va-button" href="/app/explore">Find your support<AppIcon name="arrow" size={18}/></Link>}<Link className="va-text-link" href={user ? "/app/saved" : "/app/explore"}>{user ? "See my village" : "Have a look around"} <span aria-hidden="true">↗</span></Link></div>{error && <ErrorBox message={error}/>}</div><div className="va-welcome-scene"><span className="va-scene-eyebrow">YOUR WORLD, WITH A LITTLE MORE HELP</span><VillageOrbit lit={lit}/><p>Choose a circle. Find your people.</p></div></section>
    {user && <div className="va-stats"><Link href="/app/saved"><strong>{saved.data?.providers.length ?? "—"}</strong><span>providers in your village</span><AppIcon name="heart"/></Link><Link href="/app/requests"><strong>{requests.data?.requests.filter(r => !["completed", "cancelled", "declined"].includes(r.status)).length ?? "—"}</strong><span>requests in progress</span><AppIcon name="inbox"/></Link><Link href="/app/requests"><strong>{offers.length}</strong><span>ready for your next step</span><AppIcon name="arrow"/></Link></div>}
    {offers.length > 0 && <section className="va-section"><div className="va-section-title"><div><p className="va-eyebrow">A LITTLE PROGRESS</p><h2>Your next step is here.</h2></div><Link href="/app/requests">View requests ↗</Link></div>{offers.slice(0, 2).map(request => <RequestRow key={request.id} request={request}/>)}</section>}
    <section className="va-section"><div className="va-section-title"><div><p className="va-eyebrow">START WITH WHAT WOULD HELP</p><h2>Make the everyday a little lighter.</h2></div><Link href="/app/explore">Explore all support ↗</Link></div><div className="va-need-grid">{services.slice(0, 8).map(service => <Link href={`/app/explore?category=${service.slug}`} key={service.slug}><span className={`va-need-icon village-tone-${service.tone}`}><ServiceIcon slug={service.slug}/></span><span>{service.shortTitle}</span><AppIcon name="arrow" size={16}/></Link>)}</div></section>
    <section className="va-section"><div className="va-section-title"><div><p className="va-eyebrow">{mode === "preview" ? "MEET THE EXAMPLE PROVIDERS" : "MEET YOUR LOCAL SUPPORT"}</p><h2>Good help starts with a hello.</h2></div><Link href="/app/explore">Meet everyone ↗</Link></div>{directory.error ? <ErrorBox message={directory.error} retry={directory.reload}/> : directory.loading ? <Loading/> : <div className="va-provider-grid">{directory.data?.providers.slice(0, 3).map(provider => <ProviderCard key={provider.id} provider={provider} saved={savedIds.includes(provider.id)} onSaved={saved.reload}/>)}</div>}</section>
    <div className="va-gentle-note"><AppIcon name="leaf" size={30}/><div><h2>Your village can start small.</h2><p>One meal. One helpful conversation. One thing off your list. Start wherever you are.</p></div></div></>;
}
export function Explore() {
  const { directory, saved, savedIds } = useDirectory(); const params = useSearchParams();
  const [category, setCategory] = useState(params.get("category") || ""), [query, setQuery] = useState(""), [suburb, setSuburb] = useState("");
  useEffect(() => { setCategory(params.get("category") || ""); }, [params]);
  const providers = directory.data?.providers || [];
  const suburbs = [...new Set(providers.flatMap(p => p.suburbs).filter(s => s !== "Online"))].sort();
  const filtered = providers.filter(p => (!category || p.category === category) && (!suburb || p.mode === "Online" || p.suburbs.includes(suburb)) && (!query || `${p.name} ${p.summary} ${p.suburbs.join(" ")}`.toLowerCase().includes(query.toLowerCase())));
  function reset() { setCategory(""); setQuery(""); setSuburb(""); }
  return <><Heading eyebrow="FIND YOUR PEOPLE" title="What would help you today?">Explore support that fits your household, your days and your little corner of the world.</Heading><div className="va-search-panel"><label className="va-search"><AppIcon name="search"/><span className="sr-only">Search providers</span><input type="search" placeholder="Meals, a helping hand, a provider…" value={query} onChange={e => setQuery(e.target.value)}/></label><label className="va-suburb"><AppIcon name="pin"/><span className="sr-only">Filter by suburb</span><select value={suburb} onChange={e => setSuburb(e.target.value)}><option value="">All areas</option>{suburbs.map(s => <option key={s}>{s}</option>)}</select></label></div><div className="va-filter-chips" aria-label="Support categories"><button aria-pressed={!category} onClick={() => setCategory("")}>All support</button>{services.map(s => <button key={s.slug} aria-pressed={category === s.slug} onClick={() => setCategory(s.slug)}><ServiceIcon slug={s.slug}/>{s.shortTitle}</button>)}</div>
    {directory.error ? <ErrorBox message={directory.error} retry={directory.reload}/> : directory.loading ? <Loading/> : <><div className="va-results-line"><p role="status">{filtered.length} {filtered.length === 1 ? "provider" : "providers"}{suburb && ` covering ${suburb}`}</p>{(category || suburb || query) && <button className="va-text-button" onClick={reset}>Clear filters</button>}</div>{filtered.length ? <div className="va-provider-grid">{filtered.map(provider => <ProviderCard key={provider.id} provider={provider} saved={savedIds.includes(provider.id)} onSaved={saved.reload}/>)}</div> : <><Empty title="A little more searching to do." href={category ? `/services/${category}` : "/services"} action="See existing support resources">There are no providers matching these filters yet. You can still explore the independent services on our website.</Empty><button className="va-button va-button-secondary" onClick={reset}>Show all providers</button></>}</>}
    <div className="va-directory-note"><AppIcon name="leaf"/><p>Choose who feels right for you. Profiles describe the provider’s offer; check qualifications, suitability and arrangements directly before proceeding.</p></div></>;
}
export function SavedProviders() {
  const { user } = useApp(), { saved, savedIds } = useDirectory(); const { draft } = useVillage();
  return <><Heading eyebrow="YOUR PEOPLE, TOGETHER" title="Your village, taking shape.">A little collection of support you can come back to, whenever you need it.</Heading>{!user ? <SignInPrompt/> : user.role !== "family" ? <Empty title="This space is for families." href="/app" action="Go to your workspace">Use your family account to keep your own village.</Empty> : saved.loading ? <Loading/> : saved.error ? <ErrorBox message={saved.error} retry={saved.reload}/> : saved.data?.providers.length ? <div className="va-provider-grid">{saved.data.providers.map(provider => <ProviderCard key={provider.id} provider={provider} saved={savedIds.includes(provider.id)} onSaved={saved.reload}/>)}</div> : <Empty title="Your first bit of support is out there.">Tap the heart on a provider to add them here. Saving is a shortlist, with no commitment.</Empty>}
    {draft.needs.length > 0 && <section className="va-section va-panel"><p className="va-eyebrow">FROM YOUR WEBSITE VILLAGE</p><h2>Keep exploring your choices.</h2><p>Your earlier support choices are still here. Find a provider for each, at your own pace.</p><div className="va-filter-chips">{draft.needs.map(slug => <Link key={slug} href={`/app/explore?category=${slug}`}><ServiceIcon slug={slug}/>{services.find(s => s.slug === slug)?.shortTitle}</Link>)}</div><Link className="va-text-link" href="/my-village">View your original support plan ↗</Link></section>}</>;
}
export function ProviderProfile({ id }: { id: string }) {
  const providerData = useAppData<{ provider: Listing }>(`providers/${encodeURIComponent(id)}`);
  const { user } = useApp();
  if (providerData.loading) return <Loading/>;
  if (providerData.error) return <><Heading eyebrow="FIND SUPPORT" title="Let’s find another way."/><ErrorBox message={providerData.error}/><Link className="va-button" href="/app/explore">Back to providers</Link></>;
  const provider = providerData.data?.provider; if (!provider) return null;
  return <><Link className="va-back" href="/app/explore">← Back to support</Link><div className="va-profile-hero"><div><p className="va-eyebrow">{services.find(s => s.slug === provider.category)?.shortTitle} · {provider.mode}</p><h1>{provider.name}</h1><p>{provider.summary}</p><div className="va-profile-badges"><span><AppIcon name="pin" size={16}/>{provider.suburbs.join(" · ")}</span>{provider.demo && <span>Fictional example provider</span>}</div><SaveProviderAction provider={provider}/></div><ProviderArt category={provider.category} large/></div><div className="va-profile-layout"><div><section className="va-panel"><h2>A little about this support.</h2><p>{provider.description}</p><h3>What’s included</h3><ul className="va-included">{provider.included.map(item => <li key={item}><AppIcon name="check" size={18}/>{item}</li>)}</ul></section><section className="va-panel va-profile-reassurance"><h2>Start with a conversation.</h2><p>Sending a request is free and doesn’t confirm a booking. The provider can reply with a price and proposed arrangement. You choose whether to accept.</p><p>Payments are arranged directly with the provider. Check cancellation terms and any qualifications relevant to the service before accepting.</p>{provider.demo && <p className="va-demo-copy">This profile, pricing and availability are fictional. Preview requests stay in this local app.</p>}</section></div><aside className="va-request-panel"><p className="va-eyebrow">A NEXT STEP, WHEN YOU’RE READY</p><h2>{provider.price}</h2><p>{provider.availability}</p><span className="va-updated">Profile updated {new Date(provider.updatedAt).toLocaleDateString("en-AU")}</span>{provider.status !== "published" ? <p className="va-error">This listing is not currently taking requests.</p> : !user ? <Link className="va-button" href={`/app/sign-in?next=/app/providers/${provider.id}`}>Sign in to request support<AppIcon name="arrow" size={18}/></Link> : user.role !== "family" ? <p className="va-muted">Families can send a request here. You’re viewing this as a {user.role}.</p> : <AvailabilityForm provider={provider}/>}</aside></div></>;
}
function AvailabilityForm({ provider }: { provider: Listing }) {
  const router = useRouter(); const { refresh } = useApp();
  const [busy, setBusy] = useState(false), [error, setError] = useState(""); const [key] = useState(() => crypto.randomUUID());
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError(""); const data = new FormData(event.currentTarget);
    try { const result = await appApi<{ request: SupportRequest }>("requests", { providerId: provider.id, suburb: data.get("suburb"), timing: data.get("timing"), message: data.get("message"), consent: data.get("consent") === "on", key }); refresh(); router.push(`/app/requests/${result.request.id}`); } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  return <form className="va-form" onSubmit={submit}><h3>Request availability</h3><label>Your suburb{provider.mode === "Online" ? <input name="suburb" required minLength={2} maxLength={80} autoComplete="address-level2"/> : <select name="suburb" required defaultValue=""><option value="" disabled>Choose your suburb</option>{provider.suburbs.map(s => <option key={s}>{s}</option>)}</select>}</label><label>When would help feel good?<select name="timing" required defaultValue=""><option value="" disabled>Choose a timeframe</option><option>This week</option><option>In the next few weeks</option><option>Planning ahead</option></select></label><label>A little about what you need<textarea name="message" rows={4} required minLength={10} maxLength={1500} placeholder="What would make your week easier? Include any timing or practical preferences."/></label><p className="va-field-note">Keep this practical. Please leave out medical histories and other sensitive details.</p><label className="va-checkbox"><input name="consent" type="checkbox" required/><span>Share my name, suburb, timeframe and message with {provider.name}. Village can access this request to help resolve issues.</span></label>{error && <ErrorBox message={error}/>}<button className="va-button" disabled={busy}>{busy ? "Adding your request…" : "Send availability request"}<AppIcon name="arrow" size={18}/></button><p className="va-field-note">Replies appear in Requests. Email notifications are not enabled.</p></form>;
}
