"use client";
import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import Link from "next/link";
import { appApi, useApp, useAppData } from "./AppContext";
import { AppIcon, Empty, ErrorBox, Heading, Loading, RequestRow, SignInPrompt } from "./AppUI";
import { money, requestLabels, type SupportRequest } from "@/lib/app-types";
export function Requests() {
  const { user } = useApp(); const result = useAppData<{ requests: SupportRequest[] }>("requests", !!user);
  const [filter, setFilter] = useState("all");
  if (!user) return <><Heading eyebrow="KEEP IN TOUCH" title="Your support, in conversation."/><SignInPrompt/></>;
  const requests = (result.data?.requests || []).filter(r => filter === "all" || (filter === "active" && !["completed", "declined", "cancelled"].includes(r.status)) || (filter === "completed" && r.status === "completed"));
  return <><Heading eyebrow={user.role === "family" ? "YOUR NEXT STEPS" : "YOUR INBOX"} title={user.role === "family" ? "A little closer to feeling supported." : "Good support starts here."}>Requests, replies and arrangements, all together. Replies appear here; email notifications are not enabled.</Heading><div className="va-toolbar"><div className="va-filter-chips">{[["all", "All requests"], ["active", "In progress"], ["completed", "Completed"]].map(([key, label]) => <button aria-pressed={filter === key} key={key} onClick={() => setFilter(key)}>{label}</button>)}</div><button className="va-text-button" onClick={result.reload}>Refresh inbox</button></div>{result.loading ? <Loading/> : result.error ? <ErrorBox message={result.error} retry={result.reload}/> : requests.length ? <div className="va-request-list">{requests.map(request => <RequestRow key={request.id} request={request} providerView={user.role !== "family"}/>)}</div> : <Empty title={filter === "all" ? "Your next conversation starts here." : "Nothing in this view just yet."} href={user.role === "family" ? "/app/explore" : user.role === "provider" ? "/app/partner" : "/app/owner"} action={user.role === "family" ? "Find support" : "Go to your workspace"}>{filter === "all" ? "When a family requests support, the conversation and every next step will appear here." : "Try another filter to see your other requests."}</Empty>}</>;
}
const explanations: Record<SupportRequest["status"], string> = {
  requested: "Your request is saved in the provider’s inbox. You can ask a follow-up question below.",
  offered: "The provider has suggested an arrangement. Read the details and total price before choosing your next step.",
  confirmed: "This arrangement has been accepted. Agree payment and cancellation terms directly with the provider.",
  delivered: "The provider has marked this support delivered and paid. The family can confirm that or ask for a review.",
  completed: "The family has confirmed the support was received and the provider was paid. A little more support, in place.",
  declined: "The provider couldn’t help with this request. There may be another option in your village.",
  cancelled: "This request is closed. This does not move or refund any money; contact the provider about payment.",
  disputed: "This request needs a review. Any referral fee is excluded while the issue is reviewed in the owner workspace.",
};
export function RequestDetail({ id }: { id: string }) {
  const { user, refresh } = useApp();
  const result = useAppData<{ request: SupportRequest }>(`requests/${encodeURIComponent(id)}`, !!user);
  const [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
  useEffect(() => { if (!user) return; const timer = setInterval(() => { if (document.visibilityState === "visible") result.reload(); }, 30000); return () => clearInterval(timer); }, [user, result.reload]);
  if (!user) return <SignInPrompt asTitle/>;
  if (result.loading && !result.data) return <Loading/>;
  if (result.error) return <><Heading eyebrow="YOUR REQUESTS" title="Let’s find your way back."/><ErrorBox message={result.error} retry={result.reload}/><Link className="va-button" href="/app/requests">Back to requests</Link></>;
  const request = result.data?.request; if (!request) return null;
  async function action(body: Record<string, unknown>) { setBusy(true); setError(""); setNotice(""); try { await appApi(`requests/${id}`, body); setNotice("Your update is saved."); refresh(); return true; } catch (e) { setError((e as Error).message); result.reload(); return false; } finally { setBusy(false); } }
  const family = user.role === "family", provider = user.role === "provider";
  const open = !["completed", "declined", "cancelled"].includes(request.status);
  return <><Link className="va-back" href="/app/requests">← All requests</Link><div className="va-detail-heading"><Heading eyebrow={family ? "YOUR SUPPORT REQUEST" : `REQUEST FROM ${request.familyName}`} title={request.providerName}>{request.suburb} · {request.timing}</Heading><span className={`va-status va-status-${request.status}`}>{requestLabels[request.status]}</span></div><div className="va-request-layout"><div><section className="va-panel va-status-panel"><p className="va-eyebrow">WHERE THINGS STAND</p><h2>{requestLabels[request.status]}</h2><p>{provider && request.status === "requested" ? "This family would like your support. Reply with a proposed arrangement or let them know if you cannot help." : provider && request.status === "offered" ? "Your offer is with the family. You can update it here while you wait for their decision." : explanations[request.status]}</p>{request.quoteCents !== null && <div className="va-offer-summary"><strong>{money(request.quoteCents)}<small>total, paid directly to the provider</small></strong><p>{request.arrangement}</p></div>}
    {notice && <p className="va-success" role="status"><AppIcon name="check" size={18}/>{notice}</p>}{error && <ErrorBox message={error}/>}
    {family && request.status === "offered" && <ActionForm button="Accept this arrangement" busy={busy} onSubmit={async data => { if (data.get("agree") !== "on") return; await action({ action: "accept", quoteCents: request.quoteCents, arrangement: request.arrangement }); }}><label className="va-checkbox"><input name="agree" type="checkbox" required/><span>I’ve checked the details, total price and provider’s cancellation terms, and want to go ahead.</span></label></ActionForm>}
    {provider && ["requested", "offered"].includes(request.status) && <ActionForm button={request.status === "offered" ? "Update this offer" : "Send an offer"} busy={busy} onSubmit={data => action({ action: "offer", quoteCents: Math.round(Number(data.get("amount")) * 100), arrangement: data.get("arrangement"), message: data.get("message") })}><h3>Suggest an arrangement</h3><label>Total price (AUD)<input name="amount" type="number" min="1" max="10000" step="0.01" required placeholder="140.00"/></label><label>Date, time and what’s included<input name="arrangement" required minLength={10} maxLength={400} placeholder="Tuesday 15 September, 10am · two-hour clean"/></label><label>Your reply<textarea name="message" required rows={3} minLength={5} maxLength={1500} placeholder="A little about how you can help, and any cancellation terms."/></label><p className="va-field-note">Quote the full amount payable. Include any taxes, travel and other charges.</p></ActionForm>}
    {provider && request.status === "confirmed" && <ActionForm button="Mark delivered and paid" busy={busy} onSubmit={data => action({ action: "delivered", paid: data.get("paid") === "on" })}><label className="va-checkbox"><input name="paid" required type="checkbox"/><span>The agreed support has been delivered and payment received. Ask the family to confirm.</span></label></ActionForm>}
    {family && request.status === "delivered" && <ActionForm button="Confirm support received" busy={busy} onSubmit={data => action({ action: "complete", paid: data.get("paid") === "on" })}><label className="va-checkbox"><input name="paid" required type="checkbox"/><span>I received the support and paid the provider the agreed amount.</span></label></ActionForm>}
    {user.role === "owner" && request.status === "disputed" && <ActionForm button="Close without a referral fee" busy={busy} onSubmit={data => action({ action: "resolve", message: data.get("message") })}><label>Record the resolution<textarea name="message" required minLength={10} maxLength={1500} rows={3}/></label></ActionForm>}
    {(request.status === "completed" || request.status === "cancelled" || request.status === "declined") && family && <Link href="/app/explore" className="va-button va-button-secondary">Explore more support<AppIcon name="arrow" size={18}/></Link>}
    </section><section className="va-panel"><h2>Your conversation</h2><ol className="va-messages">{request.events.map(event => <li key={event.id}><div><strong>{event.author}</strong><time dateTime={event.createdAt}>{new Date(event.createdAt).toLocaleString("en-AU", { day: "numeric", month: "short", hour: "numeric", minute: "2-digit" })}</time></div><p>{event.message}</p></li>)}</ol>{open && (family || provider) && <ActionForm busy={busy} button="Send message" clearOnSuccess onSubmit={data => action({ action: "message", message: data.get("message") })}><label>Your message<textarea name="message" required maxLength={1500} rows={3} placeholder="Keep the conversation going…"/></label></ActionForm>}</section></div>
    <aside><section className="va-panel va-request-facts"><p className="va-eyebrow">THE LITTLE DETAILS</p><h2>Request summary</h2><dl><div><dt>Family</dt><dd>{request.familyName}</dd></div><div><dt>Area</dt><dd>{request.suburb}</dd></div><div><dt>When</dt><dd>{request.timing}</dd></div><div><dt>Sent</dt><dd>{new Date(request.createdAt).toLocaleDateString("en-AU")}</dd></div><div><dt>Reference</dt><dd>{request.id.slice(0, 8).toUpperCase()}</dd></div></dl><Link className="va-text-link" href={`/app/providers/${request.providerId}`}>View provider profile ↗</Link></section>
    {(family || provider) && ["requested", "offered", "confirmed"].includes(request.status) && <details className="va-panel va-action-details"><summary>{provider && request.status !== "confirmed" ? "Unable to help?" : "Need to cancel?"}</summary><ActionForm busy={busy} button={provider && request.status !== "confirmed" ? "Decline request" : "Cancel request"} onSubmit={data => action({ action: provider && request.status !== "confirmed" ? "decline" : "cancel", message: data.get("message") })}><label>A short explanation<textarea name="message" required minLength={5} maxLength={1000} rows={3}/></label><p className="va-field-note">This closes the request in Village. Settle any payment or cancellation costs directly.</p></ActionForm></details>}
    {family && ["confirmed", "delivered", "completed"].includes(request.status) && <details className="va-panel va-action-details"><summary>Something not quite right?</summary><ActionForm button="Ask for a review" busy={busy} onSubmit={data => action({ action: "dispute", message: data.get("message") })}><label>What needs attention?<textarea name="message" required minLength={5} maxLength={1500} rows={3}/></label><p className="va-field-note">This is recorded for the provider and Village owner. It does not process a refund.</p></ActionForm></details>}
    </aside></div></>;
}
function ActionForm({ children, button, busy, onSubmit, clearOnSuccess = false }: { children: ReactNode; button: string; busy: boolean; clearOnSuccess?: boolean; onSubmit: (data: FormData) => Promise<unknown> }) {
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const result = await onSubmit(new FormData(form)); if (clearOnSuccess && result) form.reset(); }
  return <form className="va-form va-action-form" onSubmit={submit}>{children}<button className="va-button" disabled={busy}>{busy ? "Saving…" : button}<AppIcon name="arrow" size={18}/></button></form>;
}
