import { StyleSheet } from "react-native";
export const c = {
  paper: "#F8F6EF",
  cream: "#FFFDF7",
  forest: "#334F43",
  deep: "#253D35",
  sage: "#E7ECE1",
  ink: "#24372E",
  muted: "#667065",
  gold: "#ECCD87",
  goldInk: "#70531D",
  line: "#DDDCCF",
  rose: "#F2E6DF",
  danger: "#8B3932",
};
export const f = {
  body: "Jakarta",
  medium: "JakartaMedium",
  bold: "JakartaSemiBold",
  heading: "Newsreader",
  italic: "NewsreaderItalic",
};
export const s = StyleSheet.create({
  page: { flex: 1, backgroundColor: c.paper },
  content: {
    padding: 22,
    paddingBottom: 40,
    gap: 22,
    width: "100%",
    maxWidth: 620,
    alignSelf: "center",
  },
  row: { flexDirection: "row", alignItems: "center", gap: 12 },
  between: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  column: { gap: 12 },
  wrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  eyebrow: {
    fontFamily: f.bold,
    fontSize: 10,
    letterSpacing: 1.8,
    color: c.muted,
    textTransform: "uppercase",
  },
  h1: {
    fontFamily: f.heading,
    fontSize: 42,
    lineHeight: 44,
    color: c.ink,
    letterSpacing: -1,
  },
  h2: { fontFamily: f.heading, fontSize: 28, color: c.ink },
  h3: { fontFamily: f.heading, fontSize: 23, color: c.ink },
  body: { fontFamily: f.body, fontSize: 14, lineHeight: 22, color: c.muted },
  small: { fontFamily: f.body, fontSize: 11, lineHeight: 18, color: c.muted },
  label: { fontFamily: f.bold, fontSize: 12, color: c.ink },
  card: {
    backgroundColor: c.cream,
    borderColor: c.line,
    borderWidth: 1,
    borderRadius: 22,
    padding: 20,
    gap: 14,
  },
  input: {
    fontFamily: f.body,
    fontSize: 15,
    color: c.ink,
    minHeight: 52,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: c.cream,
    borderWidth: 1,
    borderColor: c.line,
    borderRadius: 14,
  },
  divider: { height: 1, backgroundColor: c.line },
  link: {
    color: c.forest,
    fontFamily: f.bold,
    fontSize: 13,
    textDecorationLine: "underline",
  },
});
